# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 510)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.089, y1:0.088, x2:0.93, y2:0.933712, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.image_label.setGeometry(QtCore.QRect(110, 10, 501, 81))
        self.image_label.setText("")
        self.image_label.setPixmap(QtGui.QPixmap("../image/indir.png"))
        self.image_label.setScaledContents(True)
        self.image_label.setObjectName("image_label")
        self.username_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.username_label.setGeometry(QtCore.QRect(380, 160, 141, 31))
        self.username_label.setStyleSheet("color:white;\n"
"font-size:20px;\n"
"border-radius:5px;")
        self.username_label.setObjectName("username_label")
        self.username_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.username_input.setGeometry(QtCore.QRect(380, 210, 201, 31))
        self.username_input.setStyleSheet("border-radius:10px;\n"
"padding:5px;\n"
"color:white")
        self.username_input.setObjectName("username_input")
        self.password_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(380, 270, 141, 31))
        self.password_label.setStyleSheet("color:white;\n"
"font-size:20px;\n"
"border-radius:5px;")
        self.password_label.setObjectName("password_label")
        self.password_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(380, 320, 201, 31))
        self.password_input.setStyleSheet("border-radius:10px;\n"
"padding:5px;\n"
"color:white")
        self.password_input.setObjectName("password_input")
        self.login_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(380, 380, 101, 41))
        self.login_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(218, 24, 58);\n"
"color:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"hover{\n"
"background-color: white;\n"
"}\n"
"\n"
"")
        self.login_button.setObjectName("login_button")
        self.exit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(520, 380, 101, 41))
        self.exit_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(218, 24, 58);\n"
"color:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"}\n"
"hover{\n"
"background-color: white;\n"
"}\n"
"\n"
"")
        self.exit_button.setObjectName("exit_button")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 290, 161, 51))
        self.label_5.setStyleSheet("color:white;\n"
"font-size:32px")
        self.label_5.setObjectName("label_5")
        self.error_mesaj_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.error_mesaj_label.setGeometry(QtCore.QRect(40, 400, 271, 31))
        self.error_mesaj_label.setText("")
        self.error_mesaj_label.setObjectName("error_mesaj_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.username_label.setText(_translate("MainWindow", "Username"))
        self.username_input.setPlaceholderText(_translate("MainWindow", "Enter your username..."))
        self.password_label.setText(_translate("MainWindow", "Password"))
        self.password_input.setPlaceholderText(_translate("MainWindow", "Enter your password..."))
        self.login_button.setText(_translate("MainWindow", "Login"))
        self.exit_button.setText(_translate("MainWindow", "EXIT"))
        self.label_5.setText(_translate("MainWindow", "CRM-V.10"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
