# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_preferences(object):
    def setupUi(self, preferences):
        preferences.setObjectName("preferences")
        preferences.resize(750, 606)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(preferences.sizePolicy().hasHeightForWidth())
        preferences.setSizePolicy(sizePolicy)
        preferences.setMinimumSize(QtCore.QSize(750, 500))
        preferences.setMaximumSize(QtCore.QSize(750, 750))
        preferences.setStyleSheet("background: qlineargradient(\n"
"    x2:0, \n"
"    y1:0, \n"
"    x1:0, \n"
"    y1:1,\n"
"    stop:0 #404040,\n"
"    stop:1 #E6E6E6\n"
");\n"
"")
        self.centralwidget = QtWidgets.QWidget(preferences)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-40, 0, 841, 581))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(500, 500))
        self.widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget.setStyleSheet("background:transparent;")
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(280, 180, 281, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_mentor_meeting = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_mentor_meeting.setStyleSheet("QPushButton {\n"
"    background-color: #D96B6B;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E07C7C;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B85A5A;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #A94444;\n"
"    font-weight: bold;\n"
"}")
        self.btn_mentor_meeting.setObjectName("btn_mentor_meeting")
        self.verticalLayout.addWidget(self.btn_mentor_meeting)
        self.btn_applications = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_applications.setStyleSheet("QPushButton {\n"
"    background-color: #D96B6B;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E07C7C;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B85A5A;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #A94444;\n"
"    font-weight: bold;\n"
"}")
        self.btn_applications.setObjectName("btn_applications")
        self.verticalLayout.addWidget(self.btn_applications)
        self.btn_interviews = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_interviews.setStyleSheet("QPushButton {\n"
"    background-color: #D96B6B;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E07C7C;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B85A5A;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #A94444;\n"
"    font-weight: bold;\n"
"}")
        self.btn_interviews.setObjectName("btn_interviews")
        self.verticalLayout.addWidget(self.btn_interviews)
        self.btn_main_menu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_main_menu.setStyleSheet("QPushButton {\n"
"    background-color: #D96B6B;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E07C7C;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B85A5A;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #A94444;\n"
"    font-weight: bold;\n"
"}")
        self.btn_main_menu.setObjectName("btn_main_menu")
        self.verticalLayout.addWidget(self.btn_main_menu)
        self.btn_exit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_exit.setStyleSheet("QPushButton {\n"
"    background-color: #D96B6B;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E07C7C;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B85A5A;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #A94444;\n"
"    font-weight: bold;\n"
"}")
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout.addWidget(self.btn_exit)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(210, 70, 391, 101))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        preferences.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(preferences)
        self.statusbar.setObjectName("statusbar")
        preferences.setStatusBar(self.statusbar)

        self.retranslateUi(preferences)
        QtCore.QMetaObject.connectSlotsByName(preferences)

    def retranslateUi(self, preferences):
        _translate = QtCore.QCoreApplication.translate
        preferences.setWindowTitle(_translate("preferences", "PREFERENCES"))
        self.btn_mentor_meeting.setText(_translate("preferences", "MENTOR MEETINGS"))
        self.btn_applications.setText(_translate("preferences", "APPLICATIONS"))
        self.btn_interviews.setText(_translate("preferences", "INTERVIEWS"))
        self.btn_main_menu.setText(_translate("preferences", "MAIN MENU"))
        self.btn_exit.setText(_translate("preferences", "EXIT"))


if __name__ == "__main__":
    data=0
    import sys
    app = QtWidgets.QApplication(sys.argv)
    preferences = QtWidgets.QMainWindow()
    ui = Ui_preferences()
    ui.setupUi(preferences)
    preferences.show()
    sys.exit(app.exec_())
