# Form implementation generated from reading ui file 'preferencesAdmin.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0208333, y1:0.045, x2:0.929924, y2:0.966, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 140, 381, 31))
        self.label.setStyleSheet("color:white;\n"
"font-size:28px;\n"
"font-weight:bold;\n"
"background-color:rgb(255, 35, 50);\n"
"border-radius:7px;\n"
"")
        self.label.setObjectName("label")
        self.image_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.image_label.setGeometry(QtCore.QRect(130, 40, 481, 71))
        self.image_label.setText("")
        self.image_label.setPixmap(QtGui.QPixmap("../image/indir.png"))
        self.image_label.setScaledContents(True)
        self.image_label.setObjectName("image_label")
        self.mein_menu_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mein_menu_button.setGeometry(QtCore.QRect(200, 210, 131, 41))
        self.mein_menu_button.setStyleSheet("QPushButton{\n"
"background-color:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"\n"
"}\n"
"\n"
"")
        self.mein_menu_button.setObjectName("mein_menu_button")
        self.admin_menu_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.admin_menu_button.setGeometry(QtCore.QRect(420, 210, 131, 41))
        self.admin_menu_button.setStyleSheet("QPushButton{\n"
"background-color:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"\n"
"}\n"
"\n"
"")
        self.admin_menu_button.setObjectName("admin_menu_button")
        self.applications_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.applications_button.setGeometry(QtCore.QRect(320, 330, 131, 41))
        self.applications_button.setStyleSheet("QPushButton{\n"
"background-color:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"\n"
"}\n"
"\n"
"")
        self.applications_button.setObjectName("applications_button")
        self.inetrviews_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.inetrviews_button.setGeometry(QtCore.QRect(110, 340, 131, 41))
        self.inetrviews_button.setStyleSheet("QPushButton{\n"
"background-color:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"\n"
"}\n"
"\n"
"")
        self.inetrviews_button.setObjectName("inetrviews_button")
        self.mentor_interviews_butoon = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mentor_interviews_butoon.setGeometry(QtCore.QRect(530, 330, 131, 41))
        self.mentor_interviews_butoon.setStyleSheet("QPushButton{\n"
"background-color:white;\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"\n"
"}\n"
"\n"
"")
        self.mentor_interviews_butoon.setObjectName("mentor_interviews_butoon")
        self.exit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(570, 430, 131, 41))
        self.exit_button.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(255, 0, 0);\n"
"border-radius:10px;\n"
"font-weight:bold;\n"
"\n"
"}\n"
"\n"
"")
        self.exit_button.setObjectName("exit_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CRM-Preferences Admin"))
        self.mein_menu_button.setText(_translate("MainWindow", "MAIN MENU"))
        self.admin_menu_button.setText(_translate("MainWindow", "ADMIN MENU"))
        self.applications_button.setText(_translate("MainWindow", "APPLICATIONS"))
        self.inetrviews_button.setText(_translate("MainWindow", "INTERVIEWS"))
        self.mentor_interviews_butoon.setText(_translate("MainWindow", "MENTOR INTERVIEWS"))
        self.exit_button.setText(_translate("MainWindow", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
